CREATE TABLE MENU_TABLE(
    MENU VARCHAR2(15) CONSTRAINT MENU_MENU_PK PRIMARY KEY,
    SANDSIZE VARCHAR2(4) CONSTRAINT MENU_SANDSIZE_FK REFERENCES SANDWICH_FK (SANDSIZE),
    SALSIZE VARCHAR(1) CONSTRAINT MENU_SALSIZE_FK REFERENCES SALAD_FK (SALSIZE)
);

CREATE TABLE SANDWICH(
    SANDSIZE VARCHAR2(4) CONSTRAINT SANDWICH_SAND_SIZE_PK PRIMARY KEY,
    BREAD VARCHAR2(25) NOT NULL,
    MAIN VARCHAR2(6) NOT NULL,
    CHEESE VARCHAR2(20),
    VEGI VARCHAR2(12),
    SOURCE VARCHAR2(20)
    );

CREATE TABLE SALAD(
    SALSIZE VARCHAR2(1) PRIMARY KEY,
    MAIN VARCHAR2(6) NOT NULL,
    CHEESE VARCHAR2(20),
    VEGI VARCHAR2(12),
    SOURCE VARCHAR2(20)
    );