CREATE TABLE DEPT_TCL 
    AS SELECT * FROM DEPT;
    
SELECT * FROM DEPT_TCL;
    
INSERT INTO DEPT_TCL VALUES(50, 'DATABASE', 'SEOUL');

UPDATE DEPT_TCL SET LOC = 'BUSAN' WHERE DEPTNO = 40;
    
DELETE FROM DEPT_TCL WHERE DNAME = 'RESEARCH';

COMMIT;

---------------------------------------
/* DDL 관련 커맨드 (데이터 정의어)
    * CREATE : 테이블 생성
    * ALTER : 테이블 변경 (ADD, RENAME, MODIFY, DROP) -> 컬럼에 영향을 주는 명령어들
    * RENAME : 테이블 이름 변경
    * TRUNCATE : 테이블의 데이터를 삭제
    * DROP : 테이블 삭제
*/

-- 테이블의 자료형을 정의하여 새로 생성하는 방법
DESC EMP;
DROP TABLE EMP_DDL;
CREATE TABLE EMP_DDL (
    EMPNO    NUMBER(4),
    ENAME    VARCHAR2(10),
    JOB      VARCHAR2(9),
    MGR      NUMBER(4),
    HIREDATE DATE,
    SAL      NUMBER(7, 2),
    COMM     NUMBER(7, 2),
    DEPTNO   NUMBER(2)
);

SELECT * FROM EMP_DDL;

-- 기존 테이블의 열 구조와 데이터를 복사하여 새 테이블 생성하기
CREATE TABLE DEPT_DDL
    AS SELECT * FROM DEPT;

SELECT * FROM DEPT_DDL;

-- 기존 테이블의 열 구조만 복사하여 새 테이블 만들기
CREATE TABLE DEPT_TMP
    AS SELECT * FROM DEPT
    WHERE 1 != 1;
    
SELECT * FROM DEPT_TMP;
SELECT * FROM EMPDEPT_DDL;

CREATE TABLE EMPDEPT_DDL
    AS SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE,
    E.SAL, E.COMM, D.DEPTNO, D.DNAME, D.LOC
    FROM EMP E, DEPT D
    WHERE 1 != 1;
    
 -------------------------------------------------------------------------------------------- --------------------------------------------------------------------------------------   
-- 테이블을 변경하는 ALTER : 테이블에 새 열을 추가 또는 삭제, 열의 자료형 길이 변경 등을 수행
CREATE TABLE EMP_ALTER  AS SELECT * FROM EMP;
SELECT * FROM EMP_ALTER;

-- 테이블에 새로운 열을 추가 : ADD, 추가된 열에 대한 행에는 NULL 값으로 입력됨
ALTER TABLE EMP_ALTER
    ADD HP VARCHAR2(20);
    
-- 열 이름 변경 : RENAME
ALTER TABLE EMP_ALTER
    RENAME COLUMN HP TO TEL;
    
-- 열의 자료형을 변경 : MODIFY, 자료형 변경 시 이미 해당 컬럼에 대한 행이 존재한다면 변경이 안될수도있음
-- 기존의 자료형의 크기보다 크게 변경하는 건 문제 안됨, 작게 변경시에는 포함된 데이터에 영향을 받음
ALTER TABLE EMP_ALTER
    MODIFY EMPNO NUMBER(5);
    
-- 특정 열을 삭제할 때 : DROP
ALTER TABLE EMP_ALTER
    DROP COLUMN TEL;
    
   ----------------------------------------------------------------------------------------- -----------------------------------------------------------------------------------------  
/* 테이블 이름을 변경하는 RENAME */

RENAME EMP_ALTER TO EMP_RENAME;
SELECT * FROM EMP_RENAME;

/* 테이블의 데이터를 삭제하는 TRUNCATE */
-- 테이블의 모든 데이터를 삭제하는 명령, 테이블 구조에 영향을 주지 않으며, ROLLBACK 불가
TRUNCATE TABLE EMP_RENAME;

/* 테이블을 삭제하는 DROP */
DROP TABLE EMP_RENAME;

-----------------------------------------------------------------------------------
-- 연습문제 

-- 1. 다음 열의 구조를 가지는 EMP_HW 테이블을 만들어 보세요.
CREATE TABLE EMP_HW (
    EMPNO NUMBER(4),
    ENAME VARCHAR2(10),
    JOB VARCHAR2(9),
    MGR NUMBER(4),
    HIREDATE DATE,
    SAL NUMBER(7,2),
    COMM NUMBER(7,2),
    DEPTNO NUMBER(2)
);

SELECT * FROM EMP_HW;

-- 2.
ALTER TABLE EMP_HW 
    ADD BIGO VARCHAR2(20);

-- 3.
ALTER TABLE EMP_HW
    MODIFY BIGO VARCHAR2(30);

-- 4.    
ALTER TABLE EMP_HW
    RENAME COLUMN BIGO TO REMARK;

-- 5.
INSERT INTO EMP_HW
    SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO, NULL
    FROM EMP;

-- 6.
DROP TABLE EMP_HW;

--------------------------------------------------------------------------------------------

/* 제약 조건 : 테이블에 저장할 데이터를 제약하는  특수한 규칙을 의미 합니다. 조건에 맞지 않는 데이터 저장 불가 */

-- 빈 값을 허용하지 않는 NOT NULL : 열에 대한 데이터와 중복여부는 상관없고 NULL 값을 허용하지 않음 (반드시 값이 입력되어야 함)

CREATE TABLE TABLE_NOTNULL (
    LOGIN_ID  VARCHAR2(20) NOT NULL,
    LOGIN_PW  VARCHAR2(20) NOT NULL,
    TEL       VARCHAR2(20) 
    );

INSERT INTO TABLE_NOTNULL(LOGIN_ID, LOGIN_PW, TEL) VALUES('곰돌이사육사',  'SPHB8250', '010-5506-4164');
INSERT INTO TABLE_NOTNULL(LOGIN_ID, LOGIN_PW, TEL) VALUES('지구오락실', '12345678', NULL);
SELECT * FROM TABLE_NOTNULL;

/* 중복되지 않는 값 : UNIQUE */
-- 열에 저장할 데이터의 중복을 허용하지 않음, 

CREATE TABLE TABLE_UNIQUE (
     LOGIN_ID  VARCHAR2(20) UNIQUE,
     LOGIN_PW  VARCHAR2(20) NOT NULL,
     TEL VARCHAR2(20)
);
INSERT INTO TABLE_UNIQUE(LOGIN_ID, LOGIN_PW, TEL) VALUES('곰돌이사육사',  'SPHB8250', '010-5506-4164');
INSERT INTO TABLE_UNIQUE(LOGIN_ID, LOGIN_PW, TEL) VALUES('NULL', '12345678', NULL);

SELECT * FROM TABLE_UNIQUE;

DROP TABLE TABLE_PK;
DROP TABLE EMP_FK;
CREATE TABLE TABLE_PK(
    LOGIN_ID VARCHAR2(20) PRIMARY KEY,
    LOGIN_PW VARCHAR(20) NOT NULL,
    TEL      VARCHAR(20)
);
INSERT INTO TABLE_PK(LOGIN_ID, LOGIN_PW, TEL) VALUES('곰돌이사육사',  'SPHB8250', '010-5506-4164');
INSERT INTO TABLE_PK(LOGIN_ID, LOGIN_PW, TEL) VALUES('NULL', '12345678', NULL);
SELECT * FROM TABLE_PK;

/* FOREIGN(외래) KEY 지정하기
  * FOREIGN KEY는 서로 다른 테이블간 관계를 정의하는데 사용하는 제약 조건 */
CREATE TABLE DEPT_FK(
    DEPTNO NUMBER(2) CONSTRAINT DEPTFK_DEPTNO_PK PRIMARY KEY,
    DNAME VARCHAR(14),
    LOC VARCHAR(13)
);
CREATE TABLE EMP_FK(    
    EMPNO NUMBER(4) CONSTRAINT EMPFK_EMPNO_PK PRIMARY KEY,
    ENAME VARCHAR2(10),
    JOB VARCHAR2(9),
    MGR NUMBER(4),
    HIREDATE DATE,
    SAL NUMBER(7, 2),
    COMM NUMBER(7, 2),
    DEPTNO NUMBER(2) CONSTRAINT EMPFK_DEPTNO_FK REFERENCES DEPT_FK (DEPTNO)
);

INSERT INTO DEPT_FK VALUES(10, '아이브', 'SEOUL');
INSERT INTO EMP_FK VALUES(9999, '안유진', '아이돌', NULL, SYSDATE, 3000, NULL, 10);

/* 데이터 형태와 범위를 정하는 CHECK */
CREATE TABLE TABLE_CHECK (
    LOGIN_ID VARCHAR2(20) CONSTRAINT TBLCK_LOGINID_PK PRIMARY KEY,
    LOGIN_PWD VARCHAR2(20) CONSTRAINT TBLCK_LOGINPW_CK CHECK (LENGTH(LOGIN_PWD) > 3),
    TEL VARCHAR2(20)
);

INSERT INTO TABLE_CHECK VALUES('지구오락실', '1234', '010-1234-5678');
SELECT * FROM TABLE_CHECK;

/* 기본값을 지정하는 DEFAULT */
CREATE TABLE TABLE_DEFAULT (
    LOGIN_ID VARCHAR2(20) CONSTRAINT TBCLK2_LOGINID_PK PRIMARY KEY,
    LOGIN_PWD VARCHAR2(20) DEFAULT '1234',
    TEL VARCHAR2(20)
);
INSERT INTO TABLE_DEFAULT VALUES('곰돌이', NULL, '010-5006-4146');
INSERT INTO TABLE_DEFAULT (LOGIN_ID, TEL) VALUES('곰돌이2', '010-1234-5678');
SELECT * FROM TABLE_DEFAULT;

-----------------------------------------연습문제-------------------------------------------------------
SELECT * FROM PRODUCT;
-- 1-1. 
CREATE TABLE PRODUCT (
    PRODUCT_ID NUMBER PRIMARY KEY,
    PRODUCT_NAME VARCHAR2(20) NOT NULL,
    REG_DATE DATE
);

-- 1-2.
INSERT INTO PRODUCT VALUES (1, 'COMPUTER', '21/01/02');
INSERT INTO PRODUCT VALUES (2, 'SMARTPHONE', '22/02/03');
INSERT INTO PRODUCT VALUES (3, 'TELEVISION', '22/07/01');

-- 1-3.
ALTER TABLE PRODUCT
    ADD WEIGHT NUMBER CONSTRAINT PRD_WEI_CK CHECK (WEIGHT >= 0)
    ADD PRICE NUMBER CONSTRAINT PRD_PRI_CK CHECK (PRICE >= 0);

DROP TABLE CUSTOMER_TABLE;
-- 2-1. 
CREATE TABLE CUSTOMER_TABLE (
    CUSTOM_ID NUMBER PRIMARY KEY,
    USER_NAME VARCHAR(12) NOT NULL,
    PHONE VARCHAR(20),
    EMAIL VARCHAR(20),
    REG_DATE DATE DEFAULT '1900/01/01'
);

-- 2-2.
ALTER TABLE CUSTOMER_TABLE
    ADD AGE NUMBER CONSTRAINT CTT_AGE_CK CHECK (AGE < 200 OR AGE > 0)
    ADD SEX VARCHAR2(1) CONSTRAINT CTT_SEX_CK CHECK (SEX IN ('M' , 'F'))
    ADD BIRTH_DATE DATE;
    
-- 2-3
ALTER TABLE CUSTOMER_TABLE
    MODIFY PHONE VARCHAR(20) UNIQUE
    MODIFY EMAIL VARCHAR(20) UNIQUE;
    
-- 2-4
ALTER TABLE CUSTOMER_TABLE
    RENAME COLUMN SEX TO GENDER;
ALTER TABLE CUSTOMER_TABLE 
    RENAME COLUMN PHONE TO MOBILE;
ALTER TABLE CUSTOMER_TABLE 
    MODIFY USER_NAME VARCHAR(20);
    
-- 2-5
INSERT INTO CUSTOMER_TABLE VALUES(1001, '하니', '010-3456-5678', 'HN@GMAIL.COM', '2022/07/22', 18, 'F', '2004/10/06');
INSERT INTO CUSTOMER_TABLE VALUES(1002, '다니엘', '010-3457-5678', 'DAN@GMAIL.COM', '2022/07/22', 17, 'F', '2005/04/11');
INSERT INTO CUSTOMER_TABLE VALUES(1003, '해린', '010-3459-5678', 'HL@GMAIL.COM', '2022/07/22', 16, 'F', '2006/05/15');
INSERT INTO CUSTOMER_TABLE VALUES(1004, '혜인', '010-5678-5678', 'HI@GMAIL.COM', '2022/07/22', 14, 'F', '2008/04/21');
INSERT INTO CUSTOMER_TABLE VALUES(1005, '예지', '010-5678-6789', 'YJ@GMAIL.COM', '2019/02/12', 23, 'F', '2000/05/26');
INSERT INTO CUSTOMER_TABLE VALUES(1006, '리아', '010-5578-6789', 'LA@GMAIL.COM', '2019/02/12', 23, 'F', '2000/07/21');
INSERT INTO CUSTOMER_TABLE VALUES(1007, '류진', '010-5578-9999', 'LJ@GMAIL.COM', '2019/02/12', 22, 'F', '2001/04/17');
INSERT INTO CUSTOMER_TABLE VALUES(1008, '채령', '010-5578-8888', 'CR@GMAIL.COM', '2019/02/12', 22, 'F', '2001/06/05');
INSERT INTO CUSTOMER_TABLE VALUES(1009, '유나', '010-4444-8888', 'YN@GMAIL.COM', '2019/02/12', 20, 'F', '2003/12/09');

SELECT * FROM CUSTOMER_TABLE;