CREATE TABLE CUSTOM_INFO(
    고객번호    NUMBER      PRIMARY KEY,
    고객이름    VARCHAR2(20) NOT NULL,
    전화번호    VARCHAR2(20)
);


CREATE TABLE ORDER_TABLE(
    ORDER_NUM NUMBER PRIMARY KEY,
    CUS_NUM NUMBER REFERENCES CUSTOM_INFO (고객번호),
    MENU_NUM NUMBER REFERENCES PRODUCT_TABLE (상품번호),
    ORDER_DATE DATE
    );
    

CREATE TABLE MENU_TABLE(
    MENU_NUM NUMBER PRIMARY KEY,
    NAME VARCHAR2(20) NOT NULL,
    MENU VARCHAR2(30) REFERENCES 상품 (분류),
    PRICE NUMBER NOT NULL
    );


INSERT INTO MENU_TABLE VALUES (1, '클럽','샐러드', 5000);
INSERT INTO ORDER_TABLE VALUES (1, 1000, 1, SYSDATE);

CREATE TABLE INGREDIENT (
    MENU    VARCHAR2(30) PRIMARY KEY,
    MENU_SIZE    VARCHAR2(1) CHECK(MENU_SIZE IN('S', 'M', 'L')) NOT NULL,
    BREAD   VARCHAR2(20) DEFAULT 'X' NOT NULL,
    CHEESE  VARCHAR2(20) DEFAULT '치즈선택안함' NOT NULL,
    VEGI    VARCHAR2(20) DEFAULT '채소선택안함' NOT NULL,
    SAUCE   VARCHAR2(20) DEFAULT '소스선택안함' NOT NULL
    );

INSERT INTO INGREDIENT VALUES('샐러드', 'M', DEFAULT,'아메리칸치즈', '양상추', '올리브유');

DROP TABLE ORDER_TABLE;
DROP TABLE MENU_TABLE;
DROP TABLE INGREDIENT;
DROP TABLE INGREDIENT;


SELECT * FROM CUSTOM_INFO;
SELECT * FROM ORDER_TABLE;
SELECT * FROM MENU_TABLE;
SELECT * FROM INGREDIENT;


SELECT *
    FROM MENU_TABLE P JOIN ORDER_TABLE O
    ON P.MENU_NUM = O.MENU_NUM;
    
SELECT *
    FROM INGREDIENT A JOIN MENU_TABLE B
    ON A.MENU = B.MENU;



